version: '3.0'
services:
  web-member:
    image: node:18.16
    container_name: web-member
    #restart: unless-stopped  # uncomment if desired
    networks:
      - net
    ports:
      - "3001:3000"
    extra_hosts:
      - "local.member.siam66.com:host-gateway"
    working_dir: /app/web
    volumes:
      - ./template_asia_fe/web/*:/app/web  # Map local project directory
    command: sh -c "npm install && npm run deploy"
    environment:
      - npm_config_project=siam66  # Merchant code, not sure check with FE
      - npm_config_env=stage       # Value = stage / prod

networks:
  net:
    driver: bridge
